
// This file contains the original sample data for the application.
// It's used by the /admin/seed page to populate the Firestore database.

export const sampleServices = [
    {
      slug: 'fridge-repair',
      title: 'Fridge & Freezer Repair',
      short_desc: 'Expert repair for all major brands of refrigerators and freezers.',
      long_desc: 'Our certified technicians diagnose and fix all common refrigerator issues, from cooling problems and strange noises to broken ice makers and water leaks. We ensure your appliance runs efficiently.',
      details: [
        'Comprehensive diagnostics',
        'Compressor and refrigerant system repair',
        'Thermostat and sensor replacement',
        'Door seal and gasket replacement',
        'Available for residential and commercial units',
      ],
      icon: 'Refrigerator', // Placeholder, not stored in DB
    },
    {
      slug: 'cctv-internet-installation',
      title: 'CCTV & Internet Installation',
      short_desc: 'Professional installation of security cameras and network infrastructure.',
      long_desc: 'We provide end-to-end solutions for your security and connectivity needs. From designing a robust CCTV layout to installing high-speed internet and Wi-Fi networks, we ensure your property is safe and connected.',
      details: [
        'Site security assessment',
        'IP and Analog camera installation',
        'Network Video Recorder (NVR) setup',
        'Structured cabling for internet',
        'Wi-Fi access point configuration',
      ],
      icon: 'Camera',
    },
    {
      slug: 'solar-systems',
      title: 'Solar Systems',
      short_desc: 'Installation and maintenance of on-grid and off-grid solar solutions.',
      long_desc: 'Harness the power of the sun with our reliable solar system installations. We cater to both residential and commercial clients, providing custom solutions that reduce your energy bills and environmental footprint.',
      details: [
        'Energy needs analysis',
        'Solar panel mounting and wiring',
        'Inverter and battery bank setup',
        'Grid-tied and off-grid configurations',
        'System maintenance and troubleshooting',
      ],
      icon: 'Sun',
    },
    {
      slug: 'ac-installation-maintenance',
      title: 'A/C Installation & Maintenance',
      short_desc: 'Keep cool with our professional air conditioner services.',
      long_desc: 'We specialize in the installation, maintenance, and repair of various types of air conditioning systems. Our team ensures optimal performance and energy efficiency for your cooling units.',
      details: [
        'Split and central A/C installation',
        'Regular cleaning and servicing',
        'Refrigerant level checks and refills',
        'Duct cleaning and inspection',
        'Thermostat installation and repair',
      ],
      icon: 'AirVent',
    },
    {
      slug: 'industrial-electronic-repair',
      title: 'Industrial Electronic Repair',
      short_desc: 'Specialized repair services for industrial machinery and control systems.',
      long_desc: 'Minimize downtime with our expert repair services for a wide range of industrial electronics, including PLCs, VFDs, and control panels. We provide component-level diagnostics and repair to get your operations back online quickly.',
      details: [
        'PLC and HMI troubleshooting',
        'Variable Frequency Drive (VFD) repair',
        'Power supply unit repair',
        'Printed Circuit Board (PCB) diagnostics',
        'On-site and workshop repair options',
      ],
      icon: 'Factory',
    },
    {
      slug: 'electrical-solutions',
      title: 'Electrical Solutions',
      short_desc: 'Comprehensive electrical wiring and installation for buildings.',
      long_desc: 'Our licensed electricians provide safe and reliable electrical solutions for new constructions and existing buildings. We handle everything from basic wiring to complete electrical system installations, adhering to the highest safety standards.',
      details: [
        'Complete house and building wiring',
        'Distribution board installation',
        'Light fixture and outlet installation',
        'Electrical system inspection and testing',
        'Safety and compliance checks',
      ],
      icon: 'Cable',
    },
    {
      slug: 'internships-training',
      title: 'Internships & Training',
      short_desc: 'Hands-on training programs for aspiring technicians.',
      long_desc: 'We are committed to fostering the next generation of technical talent. Our internship and training programs offer practical, hands-on experience in electronics repair, installations, and customer service under the guidance of experienced professionals.',
      details: [
        'Structured internship curriculum',
        'Mentorship from senior technicians',
        'Experience with real-world projects',
        'Training on modern diagnostic tools',
        'Certificate of completion',
      ],
      icon: 'GraduationCap',
    },
    {
      slug: 'graphic-design',
      title: 'Graphic Design',
      short_desc: 'Creative graphic design services to build your brand identity.',
      long_desc: 'Beyond technical services, we also offer professional graphic design to help businesses establish a strong visual presence. From logos to marketing materials, our creative team brings your vision to life.',
      details: [
        'Logo and brand identity design',
        'Business cards and letterheads',
        'Brochures, flyers, and banners',
        'Social media graphics',
        'Product packaging design',
      ],
      icon: 'PenTool',
    },
  ];
  
  export const sampleBlogPosts = [
    {
      id: "1",
      title: "5 Signs Your Refrigerator Needs a Check-Up",
      slug: "5-signs-your-refrigerator-needs-a-check-up",
      excerpt: "Don't wait for a complete breakdown. Here are five common warning signs that your fridge might be in trouble and needs professional attention.",
      content: "A noisy compressor, excessive frost, and a constantly running motor are just a few signs your fridge needs help. In this post, we'll explore the top 5 indicators that it's time to call a technician. Ignoring these can lead to more expensive repairs or even a full replacement down the line. Learn how to spot the trouble early and save yourself time and money. We'll cover everything from strange noises to temperature fluctuations, giving you the knowledge to act fast.",
      date: "2023-10-26",
      author: "HABIMANA Celestin",
      category: "Appliance Repair",
      imageUrl: "https://picsum.photos/seed/fridge-post/1200/600",
      status: 'Published' as const,
    },
    {
      id: "2",
      title: "The Benefits of a Professionally Installed CCTV System",
      slug: "benefits-of-professional-cctv-installation",
      excerpt: "Thinking about installing security cameras? Discover why a professional installation is crucial for effective surveillance and peace of mind.",
      content: "While DIY security cameras are popular, a professional installation offers significant advantages. Proper camera placement, secure wiring, and optimal NVR configuration are key for a reliable surveillance system. In this article, we discuss the importance of a site assessment, the difference between camera types, and how a professional setup ensures you have no blind spots and your footage is stored securely. Protect your property the right way.",
      date: "2023-11-15",
      author: "KSTech Team",
      category: "Security",
      imageUrl: "https://picsum.photos/seed/cctv-post/1200/600",
      status: 'Published' as const,
    },
     {
      id: "3",
      title: "Grand Opening Announcement",
      slug: "grand-opening-announcement",
      excerpt: "We are thrilled to announce the official grand opening of KSTech Solutions in Nyamata, Bugesera! Come visit us for special launch-day offers.",
      content: "The day has finally come! KING SERVICE TECH LTD is officially open for business. We are excited to bring top-tier electronics repair and IT services to the Bugesera community and beyond. Our mission is to provide reliable, high-quality technical solutions. To celebrate, we're offering a 15% discount on all services for the first month. We love what we do, and we can't wait to do what we love for you!",
      date: "2023-09-01",
      author: "HABIMANA Celestin",
      category: "Company News",
      imageUrl: "https://picsum.photos/seed/opening-post/1200/600",
      status: 'Published' as const,
    },
    {
      id: "4",
      title: "Our New Internship Program is Live!",
      slug: "new-internship-program",
      excerpt: "We are excited to launch our new internship program for aspiring technicians. Gain hands-on experience and grow your career with KSTech.",
      content: "As part of our commitment to community development, we have launched a comprehensive internship program. This is a fantastic opportunity for students and recent graduates to work alongside our experienced technicians on real-world projects. The program covers a wide range of skills, from diagnostics and repair to customer service and project management. If you are passionate about technology and eager to learn, we encourage you to apply.",
      date: "2024-01-20",
      author: "KSTech HR",
      category: "Careers",
      imageUrl: "https://picsum.photos/seed/intern-post/1200/600",
      status: 'Draft' as const,
    }
  ];
  
  export const samplePortfolioProjects = [
    {
      id: "1",
      title: "Commercial Complex Network Overhaul",
      category: "CCTV & Internet",
      description: "Designed and deployed a state-of-the-art surveillance and networking solution, ensuring robust security and high-speed connectivity for a multi-tenant commercial building.",
      imageUrl: "https://picsum.photos/seed/portfolio-1/700/500",
    },
    {
      id: "2",
      title: "Off-Grid Solar for Rural Health Clinic",
      category: "Solar Systems",
      description: "Installed a complete off-grid solar power system with battery backup for a remote health clinic, providing reliable electricity for lighting, refrigeration, and medical equipment.",
      imageUrl: "https://picsum.photos/seed/portfolio-2/700/500",
    },
    {
      id: "3",
      title: "Industrial PLC System Repair",
      category: "Industrial Electronics",
      description: "Successfully diagnosed and repaired a critical failure in a factory's main PLC control system, restoring production within 24 hours and preventing significant financial loss.",
      imageUrl: "https://picsum.photos/seed/portfolio-3/700/500",
    },
     {
      id: "4",
      title: "Residential Electrical Wiring",
      category: "Electrical Solutions",
      description: "Completed full electrical wiring for a new 5-bedroom residential property, including custom lighting fixture installation and smart home integration.",
      imageUrl: "https://picsum.photos/seed/portfolio-4/700/500",
    },
    {
      id: "5",
      title: "Restaurant Kitchen Appliance Service",
      category: "Appliance Repair",
      description: "Performed comprehensive preventative maintenance and repair on all commercial kitchen appliances for a popular local restaurant, including refrigerators, cookers, and ventilation.",
      imageUrl: "https://picsum.photos/seed/portfolio-5/700/500",
    },
    {
      id: "6",
      title: "Community Center Wi-Fi Setup",
      category: "CCTV & Internet",
      description: "Provided free public Wi-Fi access for a community center by installing and configuring a mesh network of high-capacity access points.",
      imageUrl: "https://picsum.photos/seed/portfolio-6/700/500",
    }
  ];
